### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by F4GMS** [kaefe64/Arduino_uSDX_Pico_FFT_Proj#10]
hi,
my  version arduino ide is 2.3.2 with arduino Mbed OS RP2040 installed and choose Paspberry pi pico.
I  made all the mods at the  beginning of the code. I opened "pins_arduino.h" and I copied and replaced this lines:

#define PIN_WIRE_SDA        (16u)  //I2C0
#define PIN_WIRE_SCL        (17u)  //I2C0
#define PIN_WIRE_SDA1       (18u)  //included I2C1
#define PIN_WIRE_SCL1       (19u)  //included I2C1

#define WIRE_HOWMANY    (2)  //included I2C1   default was 1
#define I2C_SDA       (digitalPinToPinName(PIN_WIRE_SDA))   //I2C0
#define I2C_SCL       (digitalPinToPinName(PIN_WIRE_SCL))   //I2C0
#define I2C_SDA1      (digitalPinToPinName(PIN_WIRE_SDA1))  //included I2C1
#define I2C_SCL1      (digitalPinToPinName(PIN_WIRE_SCL1))  //included I2C1_

but same error in file Usdr.cpp "Compilation error: 'Wire1' was not declared in this scope"
some help? Thank you.
F4GMS

**Comment by F4GMS** [comment]
finally OK but,  the following lines must also be added. problem solved
#define WIRE_HOWMANY	(2)
#define I2C_SDA			(digitalPinToPinName(PIN_WIRE_SDA))
#define I2C_SCL			(digitalPinToPinName(PIN_WIRE_SCL))
#define I2C_SDA1                   (digitalPinToPinName(PIN_WIRE_SDA1))  
#define I2C_SCL1                    (digitalPinToPinName(PIN_WIRE_SCL1))

**Comment by kaefe64** [comment]
Hi F4GMS

Thank you for trying the Arjan-5. Any feedback is welcome (look the discussion session).

It is great that you have already solved your issue.
Some lines need to be changed, others included. I put some tip on the lines comments.
If you find any wrong instruction, please inform, to help all users and myself.

Have fun
Klaus F
PY2KLA

**Comment by charudatt** [comment]
Hello

 

I am having a problem with my hardware.

 

After the initial welcome screen, the displays goes just blank.

 

I have the following connected to the PICO –

*	Si5351
*	Obviously the TFT 2.8”
*	And the Rotary Encoder.

 

Any help will be appreciated 

 

regards

Charudatt- VU2UPX
