### ISSUE TITLE
Error compiling for board Raspberry Pi

### ISSUE THREAD

**Issue by SREERAJSVT** [kaefe64/Arduino_uSDX_Pico_FFT_Proj#2]
Arduino: 1.8.20 Hourly Build 2022/04/25 09:33 (Windows 10), Board: "Raspberry Pi Pico"
 Wire

"C:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -c -g3 -nostdlib "@C:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\variants\\RASPBERRY_PI_PICO/defines.txt" "@C:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\variants\\RASPBERRY_PI_PICO/cxxflags.txt" -DARDUINO_ARCH_RP2040 -MMD -mcpu=cortex-m0plus -DARDUINO=10820 -DARDUINO_RASPBERRY_PI_PICO -DARDUINO_ARCH_MBED_RP2040 -DARDUINO_ARCH_MBED -DARDUINO_LIBRARY_DISCOVERY_PHASE=0 "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\cores\\arduino" "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\variants\\RASPBERRY_PI_PICO" "-IC:\\arduino-nightly\\libraries\\PICOUSDR\\src" "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\libraries\\SPI" "-IC:\\Users\\sreer\\OneDrive\\Documents\\Arduino\\libraries\\TFT_eSPI" "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\libraries\\Wire" "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\cores\\arduino/api/deprecated" "-IC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\cores\\arduino/api/deprecated-avr-comp" "-iprefixC:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\cores\\arduino" "@C:\\Users\\sreer\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\mbed_rp2040\\3.3.0\\variants\\RASPBERRY_PI_PICO/includes.txt" "C:\\arduino-nightly\\libraries\\PICOUSDR\\src\\uSDX_SI5351.cpp" -o "C:\\Users\\sreer\\AppData\\Local\\Temp\\arduino_build_149418\\libraries\\PICOUSDR\\uSDX_SI5351.cpp.o"

Using library PICOUSDR at version 1.0 in folder: C:\arduino-nightly\libraries\PICOUSDR 

Using library SPI in folder: C:\Users\sreer\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\3.3.0\libraries\SPI (legacy)

Using library TFT_eSPI at version 2.4.72 in folder: C:\Users\sreer\OneDrive\Documents\Arduino\libraries\TFT_eSPI 

Using library Wire in folder: C:\Users\sreer\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\3.3.0\libraries\Wire (legacy)

exit status 1

Error compiling for board Raspberry Pi Pico.

**Comment by kefeur** [comment]
I received an error message Wire1 not declared this scope during the translation. What library do I need to install for it?

**Comment by kefeur** [comment]
E:\ardu\USDX\Arduino_uSDX_Pico_FFT_Proj-master\Arduino_uSDX_Pico_FFT\uSDR.cpp: In function 'void uSDR_setup()':
E:\ardu\USDX\Arduino_uSDX_Pico_FFT_Proj-master\Arduino_uSDX_Pico_FFT\uSDR.cpp:51:3: error: 'Wire1' was not declared in this scope
   Wire1.begin();           //i2c1
   ^~~~~
E:\ardu\USDX\Arduino_uSDX_Pico_FFT_Proj-master\Arduino_uSDX_Pico_FFT\uSDR.cpp:51:3: note: suggested alternative: 'Wire'
   Wire1.begin();           //i2c1
   ^~~~~
   Wire

exit status 1

Compilation error: 'Wire1' was not declared in this scope

**Comment by SREERAJSVT** [comment]
this code is missing some lines

**Comment by avemirat** [comment]
No es posible cargar el codigo.
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\Arduino_uSDX_Pico_FFT.ino.cpp.o: In function `setup':
C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/Arduino_uSDX_Pico_FFT.ino:182: undefined reference to `_UART1_'
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\monitor.cpp.o: In function `mon_lt()':
C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/monitor.cpp:107: undefined reference to `_UART1_'
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\monitor.cpp.o: In function `mon_pt()':
C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/monitor.cpp:124: undefined reference to `_UART1_'
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\monitor.cpp.o: In function `mon_si()':
C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/monitor.cpp:96: undefined reference to `_UART1_'
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\monitor.cpp.o: In function `mon_bp()':
C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/monitor.cpp:150: undefined reference to `_UART1_'
C:\Users\HP\AppData\Local\Temp\arduino-sketch-7D03291A581229C4E7D444E9ABBA061E\sketch\monitor.cpp.o:C:\Users\HP\Desktop\Arduino_uSDX_Pico_FFT/monitor.cpp:173: more undefined references to `_UART1_' follow
collect2.exe: error: ld returned 1 exit status

exit status 1

**Comment by kaefe64** [comment]
Please, look at the .ino file comments.

**Comment by CT7ABA** [comment]
Hi
I faced the same issue and it was my fault, I didn't made the changes as described at the *.ino file.
73 de Frederico
